-- | Golden differential goldens for the wire conformance corpus (M3 plan
-- D8/D16), the @cabal test@ half of the N11 differential anchor.
--
-- The committed fixtures under @fixtures/@ (the two self-edge fixtures),
-- @fixtures/corpus/@ (generated by @scripts/gen-corpus.hs@), and the eight
-- worked-example anchors @examples/<NAME>/example.core.sexp@ (generated by
-- @scripts/gen-worked-examples.hs@) are the single
-- source of truth. Each is decoded and run through the real Haskell pipeline
-- ('Lara.Driver.runUnit'); the printed verdict must equal the pinned golden
-- bytes — the exact bytes __both__ drivers emit, cross-checked against the Lean
-- executable semantics by @scripts/differential.sh@ (the real both-drivers
-- differential). Pinning them here lets plain @cabal test@ catch regressions
-- without the Lean binary present.
--
-- The fixtures are also guarded to be canonical: @printSExpr (encodeUnit u)@ of
-- the decoded unit must reproduce the committed bytes, so a hand-edit that is
-- not canonical wire text is rejected.
--
-- Arbitration (plan Global Constraints): the Lean executable is the oracle.
-- These goldens are the agreed bytes; if @differential.sh@ ever shows Lean
-- disagreeing, that is a bug fixed with a recorded note — never a silent
-- re-annotation of a golden here.
--
-- This module reads the fixture files by relative path, so the suite must be
-- run from the package root (as @cabal test@ does).
module DifferentialSpec (differentialSpecProps) where

import Test.QuickCheck

import Lara.AST
  ( AtomPat (..)
  , Contrary (..)
  , Exception (..)
  , Label (..)
  , Pat (..)
  , Question (..)
  , Rule (..)
  , Status (..)
  , SupportTerm (..)
  , Unit (..)
  )
import Lara.Driver (runUnit)
import Lara.Prop (Prop (..), Term (..))
import Lara.Wire
  ( Verdict (..)
  , decodeUnitFile
  , encodeUnit
  , encodeVerdict
  , printSExpr
  )

-- ---------------------------------------------------------------------------
-- The corpus goldens (verdict bytes both drivers emit)
-- ---------------------------------------------------------------------------

-- | (fixture path, expected verdict bytes). The large stress fixture is checked
-- structurally instead (see 'prop_stressAccept'), so it is not listed here.
corpusGoldens :: [(FilePath, String)]
corpusGoldens =
  [ ( "fixtures/covered-self-edge.sexp"
    , "(verdict accept (labels (0 undec)) (edges (0 0)) (statuses (status (atom p) contested)))"
    )
  , ("fixtures/missing-self-edge.sexp", "(verdict reject missing-conflict)")
  , ( "fixtures/corpus/rebut-program.sexp"
    , "(verdict accept (labels (0 in) (1 out)) (edges (0 1))"
        ++ " (statuses (status (atom q) justified) (status (atom not_q) defeated)))"
    )
  , ( "fixtures/corpus/independent-accept.sexp"
    , "(verdict accept (labels (0 in) (1 in) (2 in)) (edges)"
        ++ " (statuses (status (atom p0) justified) (status (atom p1) justified)"
        ++ " (status (atom p2) justified)))"
    )
  , ("fixtures/corpus/reject-duplicate-rule.sexp", "(verdict reject duplicate-rule)")
  , ("fixtures/corpus/reject-duplicate-argument.sexp", "(verdict reject duplicate-argument)")
  , ("fixtures/corpus/reject-incomplete-argument.sexp", "(verdict reject incomplete-argument)")
  , ("fixtures/corpus/reject-missing-conflict.sexp", "(verdict reject missing-conflict)")
  , ("fixtures/corpus/reject-r1.sexp", "(verdict reject R1)")
  , ("fixtures/corpus/reject-r3.sexp", "(verdict reject R3)")
  , ("fixtures/corpus/reject-r4.sexp", "(verdict reject R4)")
  , ("fixtures/corpus/reject-r5.sexp", "(verdict reject R5)")
  , ("fixtures/corpus/reject-r6.sexp", "(verdict reject R6)")
  , ("fixtures/corpus/reject-r7.sexp", "(verdict reject R7)")
  , ("fixtures/corpus/reject-r10.sexp", "(verdict reject R10)")
  , ("fixtures/corpus/reject-r11.sexp", "(verdict reject R11)")
  , ("fixtures/corpus/reject-r12.sexp", "(verdict reject R12)")
  , ("fixtures/corpus/reject-r13.sexp", "(verdict reject R13)")
  , -- Undercut / exception conformance (M3 review item 2): the undercut accept
    -- case and its exception-scan / position-resolution reject twins — the first
    -- corpus coverage of the checker's undercut case and the exception scan.
    ( "fixtures/corpus/undercut-accept.sexp"
    , "(verdict accept (labels (0 in) (1 out)) (edges (0 1))"
        ++ " (statuses (status (atom att) justified) (status (atom c) defeated)))"
    )
  , ("fixtures/corpus/reject-undercut-missing-exception.sexp", "(verdict reject R11)")
  , ("fixtures/corpus/reject-undercut-bad-position.sexp", "(verdict reject R10)")
  , -- Strict-assurance accepts (M3 review item 5): a strict trusted assurance
    -- and a replayable strict certificate are actually accepted (all other
    -- strict-assurance fixtures are rejects).
    ( "fixtures/corpus/strict-trusted-accept.sexp"
    , "(verdict accept (labels (0 in)) (edges) (statuses (status (atom pp) justified)))"
    )
  , ( "fixtures/corpus/strict-cert-accept.sexp"
    , "(verdict accept (labels (0 in)) (edges) (statuses (status (atom pp) justified)))"
    )
  ]
    ++ workedExampleGoldens

-- | The nine worked-example anchors (M4a Task A2 plus strict-cert S1). Each
-- @examples/<NAME>/
-- example.core.sexp@ is /derived/ from its @example.lara@ + co-located policy by
-- @scripts/gen-worked-examples.hs@ (parse → elaborate → @encodeUnit@), then run
-- through both drivers by @scripts/differential.sh@. These are the exact bytes
-- both drivers emit; pinning them here lets plain @cabal test@ catch regressions
-- without the Lean binary. The reject trio (R1/R2/R3) elaborates to a
-- structurally-valid unit that the /checker/ rejects with the pinned class.
workedExampleGoldens :: [(FilePath, String)]
workedExampleGoldens =
  [ ( "examples/A/example.core.sexp"
    , "(verdict accept (labels (0 out) (1 in) (2 in) (3 in)) (edges (0 3) (1 0) (2 0) (3 0))"
        ++ " (statuses (status (atom improves (con M) (con accuracy) (con D)) defeated)))"
    )
  , ( "examples/B/example.core.sexp"
    , "(verdict accept (labels (0 undec) (1 undec)) (edges (0 1) (1 0))"
        ++ " (statuses (status (atom improves (con M) (con accuracy) (con D)) contested)"
        ++ " (status (atom not_improves (con M) (con accuracy) (con D)) contested)))"
    )
  , ( "examples/E1/example.core.sexp"
    , "(verdict accept (labels (0 in)) (edges)"
        ++ " (statuses (status (atom improves (con M) (con accuracy) (con D)) justified)))"
    )
  , ( "examples/E2/example.core.sexp"
    , "(verdict accept (labels) (edges)"
        ++ " (statuses (status (atom improves (con M) (con accuracy) (con D)) gap)))"
    )
  , ( "examples/E3/example.core.sexp"
    , "(verdict accept (labels (0 in) (1 out) (2 in) (3 in) (4 undec) (5 undec))"
        ++ " (edges (2 1) (3 1) (4 5) (5 4))"
        ++ " (statuses (status (atom improves (con M_j) (con accuracy) (con D_j)) justified)"
        ++ " (status (atom improves (con M_d) (con accuracy) (con D_d)) defeated)"
        ++ " (status (atom improves (con M_c) (con accuracy) (con D_c)) contested)"
        ++ " (status (atom not_improves (con M_c) (con accuracy) (con D_c)) contested)))"
    )
  , ("examples/R1/example.core.sexp", "(verdict reject R1)")
  , ("examples/R2/example.core.sexp", "(verdict reject R12)")
  , ("examples/R3/example.core.sexp", "(verdict reject R10)")
  , ( "examples/S1/example.core.sexp"
    , "(verdict accept (labels (0 in)) (edges)"
        ++ " (statuses (status (atom holds (con safety_invariant) (con D)) justified)))"
    )
  ]

stressFixture :: FilePath
stressFixture = "fixtures/corpus/stress-independent-120.sexp"

-- ---------------------------------------------------------------------------
-- Verdict goldens
-- ---------------------------------------------------------------------------

-- | Every corpus fixture decodes and prints exactly its pinned verdict bytes.
prop_corpusVerdicts :: Property
prop_corpusVerdicts = once (ioProperty runChecks)
  where
    runChecks :: IO Property
    runChecks = conjoin <$> mapM checkOne corpusGoldens
    checkOne (path, golden) = do
      s <- readFile path
      let got = case decodeUnitFile s of
            Left e -> "CODEC:" ++ show e
            Right u -> printSExpr (encodeVerdict (runUnit u))
      pure (counterexample path (got === golden))

-- | Every committed fixture is canonical wire text: re-encoding the decoded
-- unit reproduces the file bytes (modulo the single trailing newline).
prop_corpusCanonical :: Property
prop_corpusCanonical = once (ioProperty runChecks)
  where
    paths = stressFixture : map fst corpusGoldens
    runChecks :: IO Property
    runChecks = conjoin <$> mapM checkOne paths
    checkOne path = do
      s <- readFile path
      let reencoded = case decodeUnitFile s of
            Left e -> "CODEC:" ++ show e
            Right u -> printSExpr (encodeUnit u) ++ "\n"
      pure (counterexample path (reencoded === s))

-- ---------------------------------------------------------------------------
-- Numeric-literal canonicalization guard (M3 review item 7)
-- ---------------------------------------------------------------------------

-- | Every numeric literal ('TNum') reachable in a unit. 'encodeTerm' reprints a
-- 'TNum' verbatim, so a non-canonical @(num 01)@ round-trips byte-exactly and
-- passes 'prop_corpusCanonical' — yet the Lean driver runs at @canon = id@ while
-- the Haskell core canonicalizes, so the two drivers /diverge/ on it. The corpus
-- policy is therefore to carry no @num@ literals at all (see @scripts/gen-corpus.hs@).
numLiteralsInUnit :: Unit -> [String]
numLiteralsInUnit u =
  concatMap numsInRule (unitRules u)
    ++ concatMap numsInContrary (unitContraries u)
    ++ concatMap numsInException (unitExceptions u)
    ++ concatMap (concatMap numsInProp . snd) (unitTheories u)
    ++ concatMap (numsInProp . snd) (unitLeaves u)
    ++ concatMap (numsInST . snd) (unitArgs u)
    ++ concatMap numsInProp (unitQueries u)
  where
    numsInTerm t = case t of
      TNum s -> [s]
      TStr _ -> []
      TCon _ ts -> concatMap numsInTerm ts
    numsInPat p = case p of
      PVar _ -> []
      PLit t -> numsInTerm t
      PCon _ ps -> concatMap numsInPat ps
    numsInAPat (AtomPat _ ps) = concatMap numsInPat ps
    numsInProp (Prop _ ts) = concatMap numsInTerm ts
    numsInRule r =
      concatMap numsInAPat (rulePremises r)
        ++ numsInAPat (ruleConclusion r)
        ++ concatMap (numsInAPat . questionAnswer) (ruleQuestions r)
    numsInContrary (Contrary a b) = numsInAPat a ++ numsInAPat b
    numsInException (Exception _ ap) = numsInAPat ap
    numsInST t = case t of
      SLeaf _ -> []
      SRule _ theta prems disch _ _ ->
        concatMap (numsInTerm . snd) theta
          ++ concatMap numsInST prems
          ++ concatMap (numsInST . snd) disch

-- | No committed fixture carries any @num@ literal — the executable form of the
-- num-free corpus policy. This is the guard 'prop_corpusCanonical' cannot be:
-- a hand-added @(num 01)@ re-encodes to itself and slips past canonicity, but
-- diverges between the drivers, so it must be rejected structurally here.
prop_corpusNoNumLiterals :: Property
prop_corpusNoNumLiterals = once (ioProperty runChecks)
  where
    paths = stressFixture : map fst corpusGoldens
    runChecks :: IO Property
    runChecks = conjoin <$> mapM checkOne paths
    checkOne path = do
      s <- readFile path
      pure $ case decodeUnitFile s of
        Left e -> counterexample (path ++ ": CODEC:" ++ show e) (property False)
        Right u ->
          let nums = numLiteralsInUnit u
           in counterexample
                (path ++ ": non-policy num literals " ++ show nums)
                (nums === [])

-- | The 120-argument stress fixture: 120 independent leaf arguments, all @in@,
-- no compiled edges, 120 @justified@ statuses. Checked structurally to avoid a
-- multi-kilobyte literal golden; @scripts/differential.sh@ confirms Lean agrees
-- byte-exact.
prop_stressAccept :: Property
prop_stressAccept = once (ioProperty check)
  where
    check :: IO Property
    check = do
      s <- readFile stressFixture
      pure $ case decodeUnitFile s of
        Left e -> counterexample ("CODEC:" ++ show e) False
        Right u -> case runUnit u of
          VReject r -> counterexample ("unexpected reject: " ++ show r) (property False)
          VAccept lbls edges statuses ->
            conjoin
              [ counterexample "label count" (length lbls === 120)
              , counterexample "all in" (property (all ((== LIn) . snd) lbls))
              , counterexample "no edges" (edges === [])
              , counterexample "status count" (length statuses === 120)
              , counterexample "all justified" (property (all ((== Justified) . snd) statuses))
              ]

-- ---------------------------------------------------------------------------
-- Index
-- ---------------------------------------------------------------------------

differentialSpecProps :: [(String, IO Result)]
differentialSpecProps =
  [ ("differential corpus verdict goldens", quickCheckResult prop_corpusVerdicts)
  , ("differential corpus fixtures canonical", quickCheckResult prop_corpusCanonical)
  , ("differential corpus carries no num literals", quickCheckResult prop_corpusNoNumLiterals)
  , ("differential 120-arg stress accept", quickCheckResult prop_stressAccept)
  ]
