-- | Golden differential goldens for the wire conformance corpus (M3 plan
-- D8/D16), the @cabal test@ half of the N11 differential anchor.
--
-- The committed fixtures under @fixtures/@ (the two self-edge fixtures),
-- @fixtures/corpus/@ (generated by @scripts/gen-corpus.hs@, except the four
-- hand-authored @ord-*.sexp@ anchors noted at their entries below), and the
-- worked-example anchors @examples/<NAME>/example.core.sexp@ (generated by
-- @scripts/gen-worked-examples.hs@) are the single
-- source of truth. Each 'CheckInput' is decoded and run through the real
-- Haskell pipeline ('Lara.Driver.runCheck'); the printed identity-bearing
-- verdict must equal the pinned golden bytes — the exact bytes __both__ drivers
-- emit, cross-checked against the Lean executable semantics by
-- @scripts/differential.sh@ (the real both-drivers differential). These checks
-- let plain @cabal test@ catch regressions without the Lean binary present.
--
-- The fixtures are also guarded to be canonical:
-- @printSExpr (encodeCheckInput input)@ must reproduce the committed bytes, so
-- a hand-edit that is not canonical wire text is rejected.
--
-- The deliberately malformed envelopes under @fixtures/malformed/@ are NOT
-- part of these goldens: they are the negative half of
-- @scripts/differential.sh@ (PR #44 review C8), where both drivers must exit
-- 2 with empty stdout. One anchor, @non-canonical-theory-order.sexp@,
-- additionally pins a per-driver stderr substring there (issue #36
-- re-review): the theory-identity comparison is list-ordered on both
-- drivers, so exit-2-only cannot distinguish the canonical-order rejection
-- from 'TheoryIdentityMismatch' for that envelope.
--
-- Arbitration (plan Global Constraints): the Lean executable is the oracle.
-- These goldens are the agreed bytes; if @differential.sh@ ever shows Lean
-- disagreeing, that is a bug fixed with a recorded note — never a silent
-- re-annotation of a golden here.
--
-- This module reads the fixture files by relative path, so the suite must be
-- run from the package root (as @cabal test@ does).
module DifferentialSpec (differentialSpecProps) where

import Data.List (isInfixOf, isPrefixOf, isSuffixOf, nub, sort, stripPrefix)
import System.Directory (doesDirectoryExist, listDirectory)

import Test.QuickCheck

import Lara.AdmissionFixture (admissionOutcome)

import Lara.AST
  ( AtomPat (..)
  , Contrary (..)
  , Exception (..)
  , Label (..)
  , Pat (..)
  , Question (..)
  , Rule (..)
  , Status (..)
  , SupportTerm (..)
  , Unit (..)
  )
import Lara.Driver (runCheck)
import Lara.ExpectedJson (JValue (..), expectedJsonValue)
import Lara.Prop (Prop (..), Term (..))
import Lara.Replay (CheckInput, inputReplayId, inputUnit)
import Lara.Wire
  ( PublicStatus (..)
  , Outcome (..)
  , Verdict (..)
  , decodeCheckInputFile
  , encodeCheckInput
  , encodeReplayId
  , encodeVerdict
  , printSExpr
  )

-- ---------------------------------------------------------------------------
-- The corpus goldens (verdict bytes both drivers emit)
-- ---------------------------------------------------------------------------

-- | (fixture path, expected verdict bytes). The large stress fixture is checked
-- structurally instead (see 'prop_stressAccept'), so it is not listed here.
corpusGoldens :: [(FilePath, String)]
corpusGoldens =
  [ ( "fixtures/covered-self-edge.sexp"
    , "(verdict accept (labels (0 undec)) (edges (0 0)) (statuses (status (atom p) contested)))"
    )
  , ("fixtures/missing-self-edge.sexp", "(verdict reject missing-conflict)")
  , ( "fixtures/corpus/rebut-program.sexp"
    , "(verdict accept (labels (0 in) (1 out)) (edges (0 1))"
        ++ " (statuses (status (atom q) justified) (status (atom not_q) defeated)))"
    )
  , ( "fixtures/corpus/independent-accept.sexp"
    , "(verdict accept (labels (0 in) (1 in) (2 in)) (edges)"
        ++ " (statuses (status (atom p0) justified) (status (atom p1) justified)"
        ++ " (status (atom p2) justified)))"
    )
  , -- Duplicate-report groups (spec §4.3, issue #38): a ≡-consistent group
    -- admits normally (justified); a ≢ group quarantines its members so the
    -- dependent claim loses support and surfaces as gap (accept, not reject);
    -- the same conflict escalated by policy is the R9 data-integrity reject.
    ( "fixtures/corpus/group-consistent-accept.sexp"
    , "(verdict accept (labels (0 in)) (edges)"
        ++ " (statuses (status (atom effect (con up)) justified)))"
    )
  , ( "fixtures/corpus/group-conflict-quarantine.sexp"
    , "(verdict accept (labels) (edges)"
        ++ " (statuses (status (atom effect (con up)) gap)))"
    )
  , -- The §4.3 promotion hazard (issue #76): quarantining the sole attacker
    -- leaves the target unattacked, so the pruned graph says @justified@ — which
    -- is published as @evidence-blocked@ with that label demoted to the
    -- @conditional@ section. The unaffected query keeps its ordinary status.
    ( "fixtures/corpus/group-conflict-quarantine-attacker.sexp"
    , "(verdict accept (labels (0 in) (1 in)) (edges)"
        ++ " (statuses (status (atom concl) evidence-blocked)"
        ++ " (status (atom other) justified))"
        ++ " (conditional (status (atom concl) justified)))"
    )
  , -- The lost-edge half of the same hazard: quarantine deletes an attack
    -- /edge between two retained arguments/ (the undermine on the pruned
    -- @aT@ also carried a closure edge onto @aW@), attack completeness has
    -- nothing to say (@notk@ vs @cw@ are not contraries), and only the
    -- lost-edge seed clause catches the promotion. Cross-driver anchor for
    -- the retained-to-retained branch of the compact-index bridge (#80).
    ( "fixtures/corpus/group-quarantine-lost-edge.sexp"
    , "(verdict accept (labels (0 in) (1 in)) (edges)"
        ++ " (statuses (status (atom cw) evidence-blocked))"
        ++ " (conditional (status (atom cw) justified)))"
    )
  , -- Numeric-literal identity and multi-blocked positional regression. The
    -- attacked supports use non-canonical numeric spellings while unattacked
    -- supports and queries use canonical spellings. Both production drivers
    -- must apply canonNum, block both numeric queries, and keep the ordinary
    -- query between them out of the conditional projection.
    ( "fixtures/corpus/group-quarantine-numeric-multi-blocked.sexp"
    , "(verdict accept (labels (0 in) (1 in) (2 in) (3 in) (4 in)) (edges)"
        ++ " (statuses (status (atom score1 (num 1)) evidence-blocked)"
        ++ " (status (atom other) justified)"
        ++ " (status (atom score2 (num 2)) evidence-blocked))"
        ++ " (conditional (status (atom score1 (num 1)) justified)"
        ++ " (status (atom score2 (num 2)) justified)))"
    )
  , ("fixtures/corpus/reject-r9.sexp", "(verdict reject R9)")
  , ("fixtures/corpus/reject-duplicate-rule.sexp", "(verdict reject duplicate-rule)")
  , ("fixtures/corpus/reject-duplicate-argument.sexp", "(verdict reject duplicate-argument)")
  , ("fixtures/corpus/reject-incomplete-argument.sexp", "(verdict reject incomplete-argument)")
  , ("fixtures/corpus/reject-missing-conflict.sexp", "(verdict reject missing-conflict)")
  , ("fixtures/corpus/reject-r1.sexp", "(verdict reject R1)")
  , ("fixtures/corpus/reject-r3.sexp", "(verdict reject R3)")
  , ("fixtures/corpus/reject-r4.sexp", "(verdict reject R4)")
  , ("fixtures/corpus/reject-r5.sexp", "(verdict reject R5)")
  , ("fixtures/corpus/reject-r6.sexp", "(verdict reject R6)")
  , ("fixtures/corpus/reject-r7.sexp", "(verdict reject R7)")
  , ("fixtures/corpus/reject-r10.sexp", "(verdict reject R10)")
  , ("fixtures/corpus/reject-r11.sexp", "(verdict reject R11)")
  , ("fixtures/corpus/reject-r12.sexp", "(verdict reject R12)")
  , ("fixtures/corpus/reject-r13.sexp", "(verdict reject R13)")
  , -- Undercut / exception conformance (M3 review item 2): the undercut accept
    -- case and its exception-scan / position-resolution reject twins — the first
    -- corpus coverage of the checker's undercut case and the exception scan.
    ( "fixtures/corpus/undercut-accept.sexp"
    , "(verdict accept (labels (0 in) (1 out)) (edges (0 1))"
        ++ " (statuses (status (atom att) justified) (status (atom c) defeated)))"
    )
  , ("fixtures/corpus/reject-undercut-missing-exception.sexp", "(verdict reject R11)")
  , ("fixtures/corpus/reject-undercut-bad-position.sexp", "(verdict reject R10)")
  , -- Strict-assurance accepts (M3 review item 5): a strict trusted assurance
    -- and a replayable strict certificate are actually accepted (all other
    -- strict-assurance fixtures are rejects).
    ( "fixtures/corpus/strict-trusted-accept.sexp"
    , "(verdict accept (labels (0 in)) (edges) (statuses (status (atom pp) justified)))"
    )
  , ( "fixtures/corpus/strict-cert-accept.sexp"
    , "(verdict accept (labels (0 in)) (edges) (statuses (status (atom pp) justified)))"
    )
  , -- Replay-preflight anchors (PR #44 review C3): the runtime preflight's
    -- duplicate → unknown → unselected-certificate precedence, each rejecting
    -- as R13 before the checker runs. Every anchor's unit is checker-valid;
    -- only the replay-id backend selection differs, and lower-precedence
    -- violations ride along. This cabal-test half pins only the R13 stdout
    -- verdict (identical for all three failure kinds); the precedence itself
    -- is pinned by @scripts/differential.sh@, which byte-compares the stderr
    -- @replayFailureMessage@ line for these three anchors.
    ("fixtures/corpus/reject-preflight-duplicate-backend.sexp", "(verdict reject R13)")
  , ("fixtures/corpus/reject-preflight-unknown-backend.sexp", "(verdict reject R13)")
  , ("fixtures/corpus/reject-preflight-unselected-certificate.sexp", "(verdict reject R13)")
  , -- C11 quoted-atom anchor: the strict-cert-accept shape with a non-ASCII
    -- theory digest, so the corpus byte-compares both drivers on the
    -- quoted-atom path; the verdict is unchanged.
    ( "fixtures/corpus/strict-cert-unicode-theory.sexp"
    , "(verdict accept (labels (0 in)) (edges) (statuses (status (atom pp) justified)))"
    )
  , -- @ord\@1@ replay anchors. Unlike every other fixture in this directory
    -- these four are __hand-authored__, not emitted by @scripts/gen-corpus.hs@:
    -- they pin certificate shapes (a slot naming a theory entry, a same-slot
    -- certificate on each boundary arm) the generator has no vocabulary for.
    -- They are pinned here rather than left to @scripts/differential.sh@
    -- alone because that harness only asserts /Haskell == Lean/, never
    -- /Haskell == correct/ — and for exactly these inputs the Lean side is
    -- modelled differently on purpose (a known @ord\@1@ digest resolves to the
    -- empty theory, so the premise-only guard falls out of the context bound),
    -- which makes cross-driver agreement the weakest available evidence.
    -- Listing them here also brings them under 'prop_corpusCanonical'.
    --
    -- The premise-only pair isolates the guard: both units declare the same
    -- one-entry theory carrying the goal's left numeral, and differ only in
    -- whether the certificate cites slot 2 (@== nPrem@, the theory entry —
    -- reject) or slots 0 and 1 (the premises — accept). Free-context indexing
    -- would have accepted both.
    ( "fixtures/corpus/ord-premise-only-accept.sexp"
    , "(verdict accept (labels (0 in)) (edges)"
        ++ " (statuses (status (atom num_lt (num 0.71) (num 0.74)) justified)))"
    )
  , ("fixtures/corpus/ord-premise-only-reject.sexp", "(verdict reject R13)")
  , -- The boundary arms, each over a same-slot certificate
    -- @(ordcmp (prem 0) (prem 0))@: @num_le(A, A)@ accepts, @num_lt(A, A)@ rejects.
    ( "fixtures/corpus/ord-le-boundary-accept.sexp"
    , "(verdict accept (labels (0 in)) (edges)"
        ++ " (statuses (status (atom num_le (num 5) (num 5)) justified)))"
    )
  , ("fixtures/corpus/ord-lt-boundary-reject.sexp", "(verdict reject R13)")
  ]
    ++ workedExampleGoldens

-- | The worked-example anchors (M4a Task A2, strict-cert S1, the @ord\@1@
-- comparison-plus-bridge example S2, the M5 reinstatement/contested pair
-- E4/E5, the D3 agreement-map, and the three D1 rebuttal-replay rounds
-- round0–round2). The authoritative list is this binding itself — no count is
-- repeated in prose, so it cannot drift. Each
-- @examples/<NAME>/
-- example.core.sexp@ is /derived/ from its @example.lara@ + co-located policy by
-- @scripts/gen-worked-examples.hs@ (parse → elaborate → @encodeUnit@), then run
-- through both drivers by @scripts/differential.sh@. These are the exact bytes
-- both drivers emit; pinning them here lets plain @cabal test@ catch regressions
-- without the Lean binary. The reject trio (R1/R2/R3) elaborates to a
-- structurally-valid unit that the /checker/ rejects with the pinned class.
workedExampleGoldens :: [(FilePath, String)]
workedExampleGoldens =
  [ ( "examples/A/example.core.sexp"
    , "(verdict accept (labels (0 out) (1 in) (2 in) (3 in)) (edges (0 3) (1 0) (2 0) (3 0))"
        ++ " (statuses (status (atom improves (con M) (con accuracy) (con D)) defeated)))"
    )
  , ( "examples/B/example.core.sexp"
    , "(verdict accept (labels (0 undec) (1 undec)) (edges (0 1) (1 0))"
        ++ " (statuses (status (atom improves (con M) (con accuracy) (con D)) contested)"
        ++ " (status (atom not_improves (con M) (con accuracy) (con D)) contested)))"
    )
  , ( "examples/E1/example.core.sexp"
    , "(verdict accept (labels (0 in)) (edges)"
        ++ " (statuses (status (atom improves (con M) (con accuracy) (con D)) justified)))"
    )
  , ( "examples/E2/example.core.sexp"
    , "(verdict accept (labels) (edges)"
        ++ " (statuses (status (atom improves (con M) (con accuracy) (con D)) gap)))"
    )
  , ( "examples/E3/example.core.sexp"
    , "(verdict accept (labels (0 in) (1 out) (2 in) (3 in) (4 undec) (5 undec))"
        ++ " (edges (2 1) (3 1) (4 5) (5 4))"
        ++ " (statuses (status (atom improves (con M_j) (con accuracy) (con D_j)) justified)"
        ++ " (status (atom improves (con M_d) (con accuracy) (con D_d)) defeated)"
        ++ " (status (atom improves (con M_c) (con accuracy) (con D_c)) contested)"
        ++ " (status (atom not_improves (con M_c) (con accuracy) (con D_c)) contested)))"
    )
  , ( "examples/E4/example.core.sexp"
    , "(verdict accept (labels (0 in) (1 out) (2 in) (3 in) (4 out) (5 in) (6 in) (7 out) (8 in))"
        ++ " (edges (0 1) (1 0) (2 1) (4 3) (5 4) (7 6) (8 7))"
        ++ " (statuses (status (atom improves (con M_r) (con accuracy) (con D_r)) justified)"
        ++ " (status (atom not_improves (con M_r) (con accuracy) (con D_r)) defeated)"
        ++ " (status (atom improves (con M_u) (con accuracy) (con D_u)) justified)"
        ++ " (status (atom improves (con M_x) (con accuracy) (con D_x)) justified)))"
    )
  , ( "examples/E5/example.core.sexp"
    , "(verdict accept (labels (0 undec) (1 undec) (2 undec) (3 undec) (4 undec) (5 undec))"
        ++ " (edges (1 0) (1 2) (2 1) (4 3) (4 5) (5 4))"
        ++ " (statuses (status (atom improves (con M_v) (con accuracy) (con D_v)) contested)"
        ++ " (status (atom improves (con M_w) (con accuracy) (con D_w)) contested)"
        ++ " (status (atom improves (con M_g) (con accuracy) (con D_g)) gap)))"
    )
  , ("examples/R1/example.core.sexp", "(verdict reject R1)")
  , ("examples/R2/example.core.sexp", "(verdict reject R12)")
  , ("examples/R3/example.core.sexp", "(verdict reject R10)")
  , ( "examples/S1/example.core.sexp"
    , "(verdict accept (labels (0 in)) (edges)"
        ++ " (statuses (status (atom holds (con safety_invariant) (con D)) justified)))"
    )
  , -- S2: the @ord\@1@ comparison certificate (a1) plus the defeasible bridge
    -- rule consuming it (a2, with a1 as a sub-argument). Both args are @in@,
    -- and the justified claim is the COMPARATIVE one — the bare comparison is
    -- terminal until a rule binds it to the systems and measurand.
    ( "examples/S2/example.core.sexp"
    , "(verdict accept (labels (0 in) (1 in)) (edges)"
        ++ " (statuses (status (atom better (con sys_new) (con sys_base) (con accuracy)"
        ++ " (con imagenet_val)) justified)))"
    )
  , -- agreement-map (D3, issue #64): the genuine-disagreement pair (P1) shares
    -- the same (S,B,Q,D) atoms ⇒ rebut 2-cycle ⇒ pa/pb undec, both contested;
    -- the setting-mismatch pair (P2) differs only in the setting index ⇒ zero
    -- attacks ⇒ pc/pd in, both justified.
    ( "examples/agreement-map/example.core.sexp"
    , "(verdict accept (labels (0 undec) (1 undec) (2 in) (3 in)) (edges (0 1) (1 0))"
        ++ " (statuses (status (atom better (con apt) (con cofi) (con accuracy) (con roberta_mnli_s60)) contested)"
        ++ " (status (atom not_better (con apt) (con cofi) (con accuracy) (con roberta_mnli_s60)) contested)"
        ++ " (status (atom better (con magnitude_pruning) (con dense_baseline) (con accuracy) (con bert_glue_s50)) justified)"
        ++ " (status (atom not_better (con magnitude_pruning) (con dense_baseline) (con accuracy) (con llama_openllm_s90)) justified)))"
    )
  , ( "examples/rebuttal-replay/round0/example.core.sexp"
    , "(verdict accept (labels (0 in) (1 in)) (edges)"
        ++ " (statuses (status (atom performs (con apt) (con dense_baseline) (con openllm_avg)) justified)"
        ++ " (status (atom holds (con low_memory_footprint) (con apt)) justified)"
        ++ " (status (atom contributes (con kurtosis_salience) (con apt_llama2_7b) (con openllm_avg)) gap)))"
    )
  , ( "examples/rebuttal-replay/round1/example.core.sexp"
    , "(verdict accept (labels (0 out) (1 out) (2 in) (3 in) (4 in)) (edges (0 3) (2 0) (3 0) (4 1))"
        ++ " (statuses (status (atom performs (con apt) (con dense_baseline) (con openllm_avg)) defeated)"
        ++ " (status (atom holds (con low_memory_footprint) (con apt)) defeated)"
        ++ " (status (atom contributes (con kurtosis_salience) (con apt_llama2_7b) (con openllm_avg)) gap)))"
    )
  , ( "examples/rebuttal-replay/round2/example.core.sexp"
    , "(verdict accept (labels (0 in) (1 out) (2 out) (3 out) (4 in) (5 in) (6 in) (7 in))"
        ++ " (edges (0 3) (2 0) (3 0) (4 1) (6 2) (7 3))"
        ++ " (statuses (status (atom performs (con apt) (con dense_baseline) (con openllm_avg)) justified)"
        ++ " (status (atom holds (con low_memory_footprint) (con apt)) defeated)"
        ++ " (status (atom contributes (con kurtosis_salience) (con apt_llama2_7b) (con openllm_avg)) justified)))"
    )
  , -- The paper's running example. 'RunningExampleSpec' already pins its
    -- /shape/ (run 1 gap over an empty framework, run 2 defeated via the
    -- undercut) and byte-diffs the rendered report against
    -- @measurements/frozen/running-example.txt@; these two entries add the
    -- exact verdict bytes, which nothing pinned before
    -- 'prop_goldensCoverAnchors' surfaced them.
    ( "examples/running-example/run1/example.core.sexp"
    , "(verdict accept (labels) (edges)"
        ++ " (statuses (status (atom improves (con M) (con accuracy) (con D)) gap)))"
    )
  , ( "examples/running-example/run2/example.core.sexp"
    , "(verdict accept (labels (0 out) (1 in)) (edges (1 0))"
        ++ " (statuses (status (atom improves (con M) (con accuracy) (con D)) defeated)))"
    )
  ]

stressFixture :: FilePath
stressFixture = "fixtures/corpus/stress-independent-120.sexp"

-- ---------------------------------------------------------------------------
-- Verdict goldens
-- ---------------------------------------------------------------------------

-- | Every corpus fixture decodes and prints its pinned outcome under the exact
-- replay identity carried by that fixture.
prop_corpusVerdicts :: Property
prop_corpusVerdicts = once (ioProperty runChecks)
  where
    runChecks :: IO Property
    runChecks = conjoin <$> mapM checkOne corpusGoldens
    checkOne (path, outcomeTail) = do
      bytes <- readFile path
      let got = case decodeCheckInputFile bytes of
            Left err -> "CODEC:" ++ show err
            Right input -> printSExpr (encodeVerdict (runCheck input))
          expected = case decodeCheckInputFile bytes of
            Left err -> "CODEC:" ++ show err
            Right input -> expectedVerdictText input outcomeTail
      pure (counterexample path (got === expected))

-- | The two Haskell-only presentation details that originally escaped the wire
-- golden: @expected.json@ must publish the blocked status (with the smaller
-- graph's label only as a conditional diagnostic), and its argument labels must
-- use checked-program indices after the quarantined @a2@ disappears. A revert
-- of either consumer fix leaves 'prop_corpusVerdicts' green, so pin the complete
-- affected arrays here.
prop_quarantineExpectedJson :: Property
prop_quarantineExpectedJson = once $ ioProperty $ do
  bytes <- readFile quarantineAttackerFixture
  pure $ case decodeCheckInputFile bytes of
    Left err -> counterexample ("CODEC:" ++ show err) False
    Right input ->
      case expectedJsonValue input of
        JObject top ->
          case lookup "located-diagnostic" top of
            Just (JObject diag) ->
              conjoin
                [ counterexample "public and conditional statuses" $
                    lookup "statuses" diag === Just (JArray expectedStatuses)
                , counterexample "checked-program argument labels" $
                    lookup "labels" diag === Just (JArray expectedLabels)
                ]
            other -> counterexample ("located-diagnostic: " ++ show other) False
        other -> counterexample ("expected.json root: " ++ show other) False
  where
    expectedStatuses =
      [ JObject
          [ ("claim", JString "concl")
          , ("status", JString "evidence-blocked")
          , ("complete-support", JNumber 1)
          , ("holes", JNumber 0)
          , ("incomplete-alternative", JBool False)
          , ("conditional-status", JString "justified")
          ]
      , JObject
          [ ("claim", JString "other")
          , ("status", JString "justified")
          , ("complete-support", JNumber 1)
          , ("holes", JNumber 0)
          , ("incomplete-alternative", JBool False)
          ]
      ]
    expectedLabels =
      [ JObject [("arg", JString "a1"), ("index", JNumber 0), ("label", JString "in")]
      , JObject [("arg", JString "a3"), ("index", JNumber 1), ("label", JString "in")]
      ]

quarantineAttackerFixture :: FilePath
quarantineAttackerFixture = "fixtures/corpus/group-conflict-quarantine-attacker.sexp"

expectedVerdictText :: CheckInput -> String -> String
expectedVerdictText input identityFreeVerdict =
  case stripPrefix "(verdict " identityFreeVerdict of
    Just outcomeTail ->
      "(verdict "
        ++ printSExpr (encodeReplayId (inputReplayId input))
        ++ " "
        ++ outcomeTail
    Nothing -> error ("malformed outcome golden: " ++ identityFreeVerdict)

-- | Every committed fixture is canonical wire text: re-encoding the decoded
-- unit reproduces the file bytes (modulo the single trailing newline).
prop_corpusCanonical :: Property
prop_corpusCanonical = once (ioProperty runChecks)
  where
    paths = stressFixture : map fst corpusGoldens
    runChecks :: IO Property
    runChecks = conjoin <$> mapM checkOne paths
    checkOne path = do
      s <- readFile path
      let reencoded = case decodeCheckInputFile s of
            Left e -> "CODEC:" ++ show e
            Right input -> printSExpr (encodeCheckInput input) ++ "\n"
      pure (counterexample path (reencoded === s))

-- ---------------------------------------------------------------------------
-- Numeric-literal canonicalization regression
-- ---------------------------------------------------------------------------

-- | Every numeric literal ('TNum') reachable in a unit. 'encodeTerm' reprints a
-- 'TNum' verbatim, so this lets the regression assert that its surface variants
-- remain present rather than being normalized away by fixture generation.
numLiteralsInUnit :: Unit -> [String]
numLiteralsInUnit u =
  concatMap numsInRule (unitRules u)
    ++ concatMap numsInContrary (unitContraries u)
    ++ concatMap numsInException (unitExceptions u)
    ++ concatMap (concatMap numsInProp . snd) (unitTheories u)
    ++ concatMap (numsInProp . snd) (unitLeaves u)
    ++ concatMap (numsInST . snd) (unitArgs u)
    ++ concatMap numsInProp (unitQueries u)
  where
    numsInTerm t = case t of
      TNum s -> [s]
      TStr _ -> []
      TCon _ ts -> concatMap numsInTerm ts
    numsInPat p = case p of
      PVar _ -> []
      PLit t -> numsInTerm t
      PCon _ ps -> concatMap numsInPat ps
    numsInAPat (AtomPat _ ps) = concatMap numsInPat ps
    numsInProp (Prop _ ts) = concatMap numsInTerm ts
    numsInRule r =
      concatMap numsInAPat (rulePremises r)
        ++ numsInAPat (ruleConclusion r)
        ++ concatMap (numsInAPat . questionAnswer) (ruleQuestions r)
    numsInContrary (Contrary a b) = numsInAPat a ++ numsInAPat b
    numsInException (Exception _ ap) = numsInAPat ap
    numsInST t = case t of
      SLeaf _ -> []
      SRule _ theta prems disch _ _ ->
        concatMap (numsInTerm . snd) theta
          ++ concatMap numsInST prems
          ++ concatMap (numsInST . snd) disch

-- | The production differential anchor deliberately retains non-canonical and
-- canonical spellings of each value. Removing the variants would make the
-- cross-driver test pass without exercising the identity boundary.
prop_numericCanonicalizationAnchor :: Property
prop_numericCanonicalizationAnchor = once (ioProperty check)
  where
    path = "fixtures/corpus/group-quarantine-numeric-multi-blocked.sexp"
    check = do
      bytes <- readFile path
      pure $ case decodeCheckInputFile bytes of
        Left e -> counterexample (path ++ ": CODEC:" ++ show e) False
        Right input ->
          let nums = numLiteralsInUnit (inputUnit input)
           in counterexample (path ++ ": numeric surfaces " ++ show nums) $
                nums === ["01.0", "1", "+02.00", "2", "1", "2"]

-- | The 120-argument stress fixture: 120 independent leaf arguments, all @in@,
-- no compiled edges, 120 @justified@ statuses. Checked structurally to avoid a
-- multi-kilobyte literal golden; @scripts/differential.sh@ confirms Lean agrees
-- byte-exact.
prop_stressAccept :: Property
prop_stressAccept = once (ioProperty check)
  where
    check :: IO Property
    check = do
      s <- readFile stressFixture
      pure $ case decodeCheckInputFile s of
        Left e -> counterexample ("CODEC:" ++ show e) False
        Right input -> case verdictOutcome (runCheck input) of
          Reject rejection -> counterexample ("unexpected reject: " ++ show rejection) (property False)
          Accept labels edges statuses ->
            conjoin
              [ counterexample "label count" (length labels === 120)
              , counterexample "all in" (property (all ((== LIn) . snd) labels))
              , counterexample "no edges" (edges === [])
              , counterexample "status count" (length statuses === 120)
              , counterexample "all justified" (property (all ((== Published Justified) . snd) statuses))
              ]

-- ---------------------------------------------------------------------------
-- Source admission oracle (metatheory plan Task 3)
-- ---------------------------------------------------------------------------

-- | The manifest is the exact admission corpus and declares each outcome
-- class. Its filename set must equal the directory's @*.sexp@ set, so a
-- missing or unlisted fixture cannot silently change differential coverage.
-- Every non-codec fixture is also verified against its committed @expected@
-- section by the shared Haskell semantic adapter. The proved Lean evaluator
-- is checked byte-exactly by @scripts/admission-differential.sh@; production
-- source/checker behavior is covered separately in @AdmissionSpec@.
prop_admissionOracle :: Property
prop_admissionOracle = once (ioProperty runChecks)
  where
    manifestPath = "fixtures/admission/MANIFEST"

    runChecks :: IO Property
    runChecks = do
      manifestText <- readFile manifestPath
      directoryEntries <- listDirectory "fixtures/admission"
      let emptyMarkerRows =
            [ ("empty Haskell marker", "empty-hs.sexp\tcodec-reject\t\tlean marker")
            , ("empty Lean marker", "empty-lean.sexp\tcodec-reject\thaskell marker\t")
            ]
          acceptedEmptyMarkers =
            [ label
            | (label, row) <- emptyMarkerRows
            , Right _ <- [parseManifest row]
            ]
      if not (null acceptedEmptyMarkers)
        then
          pure
            ( counterexample
                ("manifest parser accepted " ++ show acceptedEmptyMarkers)
                False
            )
        else
          case parseManifest manifestText of
            Left err -> pure (counterexample err False)
            Right cases -> checkCases directoryEntries cases

    checkCases directoryEntries cases = do
      let names = map (\(name, _, _, _) -> name) cases
          outcomeClasses = map (\(_, outcomeClass, _, _) -> outcomeClass) cases
          requiredClasses = ["accepted", "rejected", "invalid", "codec-reject"]
          missingClasses = filter (`notElem` outcomeClasses) requiredClasses
          manifestFiles = sort (map ("fixtures/admission/" ++) names)
          actualFiles =
            sort
              ( map ("fixtures/admission/" ++)
                  (filter (".sexp" `isSuffixOf`) directoryEntries)
              )
          duplicateNames = length names /= length (nub names)
      if not (null missingClasses)
        then pure (counterexample (manifestPath ++ ": missing outcome classes " ++ show missingClasses) False)
        else if duplicateNames
        then pure (counterexample (manifestPath ++ ": duplicate fixture name") False)
        else
          if manifestFiles /= actualFiles
            then
              pure
                ( counterexample
                    ( manifestPath
                        ++ " does not match fixtures/admission/*.sexp\nmanifest: "
                        ++ show manifestFiles
                        ++ "\nactual: "
                        ++ show actualFiles
                    )
                    False
                )
            else conjoin <$> mapM checkOne cases

    parseManifest :: String -> Either String [(FilePath, String, String, String)]
    parseManifest input =
      fmap foldRows (mapM parseRow (zip [1 :: Int ..] (lines input)))
      where
        foldRows = foldr (\row rows -> maybe rows (: rows) row) []
        parseRow (lineNo, line)
          | null line = Right Nothing
          | "#" `isPrefixOf` line = Right Nothing
          | otherwise =
              case splitTabs line of
                [name, outcomeClass, hsMarker, leanMarker]
                  | not (".sexp" `isSuffixOf` name) ->
                      Left (manifestPath ++ ":" ++ show lineNo ++ ": fixture must end in .sexp")
                  | outcomeClass `notElem` ["accepted", "rejected", "invalid", "codec-reject"] ->
                      Left (manifestPath ++ ":" ++ show lineNo ++ ": unknown outcome class " ++ outcomeClass)
                  | null hsMarker || null leanMarker ->
                      Left (manifestPath ++ ":" ++ show lineNo ++ ": empty stderr marker")
                  | outcomeClass == "codec-reject" && (hsMarker == "-" || leanMarker == "-") ->
                      Left (manifestPath ++ ":" ++ show lineNo ++ ": codec-reject lacks stderr markers")
                  | outcomeClass /= "codec-reject" && (hsMarker /= "-" || leanMarker /= "-") ->
                      Left (manifestPath ++ ":" ++ show lineNo ++ ": non-codec row carries stderr markers")
                  | otherwise -> Right (Just (name, outcomeClass, hsMarker, leanMarker))
                _ -> Left (manifestPath ++ ":" ++ show lineNo ++ ": expected four tab-separated fields")

        splitTabs [] = [""]
        splitTabs value =
          case break (== '\t') value of
            (field, []) -> [field]
            (field, _ : rest) -> field : splitTabs rest

    checkOne :: (FilePath, String, String, String) -> IO Property
    checkOne (name, outcomeClass, hsMarker, _) = do
      let path = "fixtures/admission/" ++ name
      contents <- readFile path
      pure $
        case (outcomeClass, admissionOutcome contents) of
          ("codec-reject", Left err) ->
            let diagnostic = "check-admission: codec error at " ++ err
             in counterexample (path ++ ": wrong codec diagnostic\n" ++ diagnostic) $
                  property (hsMarker `isInfixOf` diagnostic)
          ("codec-reject", Right _) ->
            counterexample (path ++ ": expected a codec rejection") False
          (_, Left err) -> counterexample (path ++ "\n" ++ err) False
          (_, Right (computed, expected)) ->
            conjoin
              [ counterexample (path ++ "\ncomputed: " ++ computed ++ "\nexpected: " ++ expected) $
                  computed === expected
              , counterexample (path ++ ": expected outcome class " ++ outcomeClass ++ "\n" ++ computed) $
                  property (("(" ++ outcomeClass ++ " ") `isPrefixOf` computed)
              ]

-- ---------------------------------------------------------------------------
-- Index
-- ---------------------------------------------------------------------------

-- | Every committed anchor is actually pinned above.
--
-- @scripts/differential.sh@ /glob-discovers/ its inputs, so a new fixture is
-- picked up there automatically and silently — but it only asserts
-- /Haskell == Lean/. 'corpusGoldens' is the only place either driver is
-- checked against /expected/ bytes, and it is a hand-maintained list, so a new
-- anchor stays unpinned unless someone remembers. That is exactly how the four
-- @ord-*.sexp@ fixtures and @examples/S2@ shipped unpinned (PR #83 review).
-- This closes the loop: adding an anchor without a golden now fails
-- @cabal test@ with the missing paths named.
prop_goldensCoverAnchors :: Property
prop_goldensCoverAnchors = once (ioProperty coverageCheck)
  where
    -- The one corpus fixture checked structurally instead of byte-wise
    -- ('prop_stressAccept'): its verdict is 120 labels wide.
    exempt :: [FilePath]
    exempt = [stressFixture]

    coverageCheck :: IO Property
    coverageCheck = do
      corpusEntries <- listDirectory "fixtures/corpus"
      exampleAnchors <- coreAnchorsUnder "examples"
      let corpusAnchors =
            ["fixtures/corpus/" ++ e | e <- corpusEntries, ".sexp" `isSuffixOf` e]
          pinned = map fst corpusGoldens
          missing =
            sort
              [ a
              | a <- corpusAnchors ++ exampleAnchors
              , a `notElem` pinned
              , a `notElem` exempt
              ]
      -- Empty anchor lists mean the directories moved; fail loudly rather
      -- than pass vacuously.
      pure
        ( counterexample
            ("anchors present but absent from corpusGoldens: " ++ show missing)
            (null missing)
            .&&. counterexample "no corpus anchors discovered" (not (null corpusAnchors))
            .&&. counterexample "no example anchors discovered" (not (null exampleAnchors))
        )

    -- Every @example.core.sexp@ at any depth (the suite nests
    -- rebuttal-replay/roundN and running-example/runN).
    coreAnchorsUnder :: FilePath -> IO [FilePath]
    coreAnchorsUnder dir =
      listDirectory dir >>= fmap concat . mapM (visitEntry dir)

    visitEntry :: FilePath -> FilePath -> IO [FilePath]
    visitEntry dir entry = do
      let path = dir ++ "/" ++ entry
      isDir <- doesDirectoryExist path
      if isDir
        then coreAnchorsUnder path
        else pure [path | entry == "example.core.sexp"]

differentialSpecProps :: [(String, IO Result)]
differentialSpecProps =
  [ ("differential corpus verdict goldens", quickCheckResult prop_corpusVerdicts)
  , ("every committed anchor is pinned by a golden", quickCheckResult prop_goldensCoverAnchors)
  , ("quarantine expected.json keeps public status and checked label indices", quickCheckResult prop_quarantineExpectedJson)
  , ("differential corpus fixtures canonical", quickCheckResult prop_corpusCanonical)
  , ("differential numeric canonicalization anchor retains surface variants", quickCheckResult prop_numericCanonicalizationAnchor)
  , ("differential 120-arg stress accept", quickCheckResult prop_stressAccept)
  , ("source admission fixtures match their committed oracles", quickCheckResult prop_admissionOracle)
  ]
