# Convenience targets. The repo's source of truth stays cabal + scripts/;
# these wrap the common entry points.

.PHONY: build test bench bench-image bench-container measure presentation-parity surface-conformance surface-conformance-gate-test semantics-goldens backend-deps-golden update-goldens update-differential ara-source-spans

build:
	cabal build all
	cd lean && lake build

test:
	cabal test all --test-show-details=direct

# Cross-language presentation-AST shape parity (result 12): both runtimes emit
# the same normalized ordered inventory, protected by compiler witnesses and
# shape tripwires; the gate rebuilds both and diffs them.
presentation-parity:
	bash scripts/check-presentation-parity.sh

# Independently parse/lower the concrete surface in Haskell and construct/check
# the matching presentation AST in Lean, then compare both canonical tables to
# one committed manifest-complete golden.
surface-conformance:
	bash scripts/check-surface-conformance.sh

# Regression tests for atomic update, failed-update cleanup, and check-mode
# immutability. All update exercises use a private temporary golden.
surface-conformance-gate-test:
	bash test/surface-conformance-gate.sh

# Lean-emitted extension-semantics goldens must match the checked-in Haskell
# conformance table byte for byte.
semantics-goldens:
	bash scripts/check-semantics-goldens.sh

# The Lean-emitted `certDeps` of the shipped nd@1/ord@1 mixed term must match
# the committed golden byte for byte; test/StrictSpec.hs asserts the same bytes
# from the Haskell collector. Both halves run on the shipped backend cores — the
# ord@1 acceptance blocker does not reach a dependency report.
backend-deps-golden:
	bash scripts/check-backend-deps-golden.sh

# Lean-emitted source-update matrices must match the committed report byte for
# byte. Pass UPDATE=1 to regenerate the golden deterministically.
update-goldens:
	bash scripts/check-update-goldens.sh $(if $(UPDATE),--update,check)

# Haskell and Lean must agree on every finite constructor-precondition input
# generated by their native Lara.Update mirrors.
update-differential:
	bash scripts/update-differential.sh

# Every repository-local path:line[-line] quotation in the ARA must still match
# the cited source span.
ara-source-spans:
	python3 scripts/check_ara_source_spans.py

# E1 checker-performance bench (issue #69): measures the production checker
# on the frozen corpus units and the manifest-discovered harness, prints the
# performance table, and writes the raw measurements/bench.json (gitignored).
#
# No rendered table is committed here — a table is only valid for the machine
# and commit that produced it. Print the one the consumer needs:
#
#   make bench
#   make bench FORMAT=markdown
#   make bench FORMAT=latex OUT=../paper/tables/performance.tex
FORMAT ?= text
OUT ?=
bench:
	cabal build exe:lara exe:lara-bench
	cd lean && lake build
	cabal run exe:lara-bench -- --format=$(FORMAT) $(if $(OUT),--out $(OUT),)

BENCH_IMAGE ?= lara-bench:$(shell git rev-parse --short=12 HEAD)
BENCH_ARGS ?=
bench-image:
	docker build --platform linux/arm64 --build-arg LARA_GIT_REV=$(shell git rev-parse HEAD) -f containers/bench/Dockerfile -t $(BENCH_IMAGE) .

bench-container:
	python3 scripts/bench_container.py $(BENCH_ARGS)

# The full axis-(c) measurement harness (M5): measurements/report.{json,tsv}
# and ablation reports.
measure:
	cabal exec -- runghc scripts/measure.hs
