-- | The paper's running example (fig:example) as two checked programs, with
-- their checker reports rendered for pasting into the paper (P6, issue #70).
--
-- Run 1 (@examples\/running-example\/run1@) declares the claim and its
-- evidence leaves, including the recorded dead end @e4@, but the mandatory
-- @external_validity@ critical question has no discharging leaf, so no
-- complete support argument can be declared: the claim is @gap@. (Declaring
-- @a1@ with the mandatory question as an explicit hole is not the gap path:
-- the checker rejects that program as an incomplete argument — the
-- open-obligation gate the no-CQ ablation removes.) Run 2
-- (@…\/run2@) adds the discharging leaf @e6@, so @a1@ completes, the dead
-- end lowers to the undercut @d1@, and the claim flips to @defeated@.
--
-- The rendered document reproduces the @lara check@ CLI bytes exactly: the
-- CLI prints @printSExpr (encodeVerdict verdict)@ plus one newline
-- ("app\/Main.hs"), and 'checkRun' uses the same opaque prepared source path.
-- The freshness test ("test\/RunningExampleSpec.hs") re-renders and requires
-- byte equality with the committed golden
-- (@measurements\/frozen\/running-example.txt@), the house discipline for
-- generated deliverables.
module Lara.RunningExample
  ( runPaths
  , loadRun
  , checkRun
  , renderRuns
  , goldenPath
  ) where

import Lara.AST (PolicyId (..), programPolicy)
import Lara.Admission (renderAdmissionRejection)
import Lara.Elaborate
  ( PreparedSource (..)
  , prepareSource
  , renderSourceInvalid
  , runSourceCheck
  , sourceResultVerdict
  )
import qualified Lara.Syntax as Syntax
import Lara.Wire (Outcome (..), Verdict (..), encodeVerdict, printSExpr)

-- | The two run programs, in paper order.
runPaths :: [FilePath]
runPaths =
  [ "examples/running-example/run1/example.lara"
  , "examples/running-example/run2/example.lara"
  ]

-- | The committed golden this module's rendering is pinned against.
goldenPath :: FilePath
goldenPath = "measurements/frozen/running-example.txt"

-- | Read a run's program text and its co-located policy text (the CLI's
-- policy-resolution convention: @\<policyId\>.policy.lara@ next to the
-- program).
loadRun :: FilePath -> IO (String, String)
loadRun path = do
  progText <- readFile path
  policyId <- case Syntax.parseProgram progText of
    Left _ -> pure "unresolved"
    Right prog -> let PolicyId pid = programPolicy prog in pure pid
  polText <- readFile (dirOf path ++ policyId ++ ".policy.lara")
  pure (progText, polText)
  where
    dirOf p = reverse (dropWhile (/= '/') (reverse p))

-- | The CLI's @.lara@ pipeline, pure over the two file texts: parse both,
-- elaborate, validate the replay identity, check. Left is a boundary
-- failure (the CLI's exit-2 class), Right the verdict the CLI prints.
checkRun :: String -> String -> Either String Verdict
checkRun progText polText = do
  prog <- either (Left . ("parse error: " ++) . Syntax.peReason) Right (Syntax.parseProgram progText)
  pol <- either (Left . ("policy parse error: " ++) . Syntax.peReason) Right (Syntax.parsePolicy polText)
  prepared <- either (Left . ("source invalid: " ++) . renderSourceInvalid) Right
    (prepareSource prog pol)
  case prepared of
    SourceRejected rejection -> Left ("admission rejection: " ++ renderAdmissionRejection rejection)
    SourceAccepted input -> pure (sourceResultVerdict (runSourceCheck input))

-- | Render the pinned document: for each run, the CLI command line, the
-- exact verdict bytes the CLI prints, and the CLI exit code.
renderRuns :: [(FilePath, Verdict)] -> String
renderRuns runs =
  unlines
    ( [ "Running-example checker reports (paper fig:example)."
      , "Generated by scripts/render-running-example.hs; do not edit:"
      , "test/RunningExampleSpec.hs pins this file byte-for-byte."
      , ""
      ]
        ++ concatMap renderRun runs
    )
  where
    renderRun (path, verdict) =
      [ "$ lara check " ++ path
      , printSExpr (encodeVerdict verdict)
      , "[exit " ++ show (exitCodeOf verdict) ++ "]"
      , ""
      ]
    exitCodeOf v = case verdictOutcome v of
      Accept {} -> 0 :: Int
      Reject {} -> 1
